import { jsPDF } from "jspdf";

export type ReportPatient = {
  doctorName: string;
  patientName: string;
  patientId: string;
};

export type ReportScan = {
  imageName: string;
  imageUrl: string;
  probability: number;
  prediction: number;
  pathology: string;
  notes?: string | null;
  createdAt?: string | null;
};

export type ReportOptions = {
  patient: ReportPatient;
  scan: ReportScan;
  aiSummary?: string | null;
};

// Brand palette mirrors the app's medical-blue design system.
const BRAND = {
  primary: [37, 99, 167] as const, // ~ oklch(0.46 0.13 240)
  primaryGlow: [88, 152, 214] as const, // ~ oklch(0.62 0.15 235)
  ink: [28, 41, 64] as const,
  inkSoft: [82, 96, 122] as const,
  border: [220, 226, 235] as const,
  surface: [248, 250, 253] as const,
  success: [46, 139, 87] as const,
  warning: [197, 129, 30] as const,
  white: [255, 255, 255] as const,
};

function setFill(doc: jsPDF, rgb: readonly [number, number, number]) {
  doc.setFillColor(rgb[0], rgb[1], rgb[2]);
}
function setStroke(doc: jsPDF, rgb: readonly [number, number, number]) {
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
}
function setText(doc: jsPDF, rgb: readonly [number, number, number]) {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}

async function imageToDataUrl(src: string): Promise<{
  dataUrl: string;
  width: number;
  height: number;
}> {
  return await new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      const ctx = canvas.getContext("2d");
      if (!ctx) {
        reject(new Error("Could not create canvas context."));
        return;
      }
      ctx.drawImage(img, 0, 0);
      resolve({
        dataUrl: canvas.toDataURL("image/jpeg", 0.92),
        width: img.naturalWidth,
        height: img.naturalHeight,
      });
    };
    img.onerror = () => reject(new Error("Could not load image for PDF."));
    img.src = src;
  });
}

function drawHeader(doc: jsPDF, pageWidth: number) {
  // Gradient-feel header band: solid primary with a thin accent stripe below.
  setFill(doc, BRAND.primary);
  doc.rect(0, 0, pageWidth, 26, "F");
  setFill(doc, BRAND.primaryGlow);
  doc.rect(0, 26, pageWidth, 1.4, "F");

  // Logo mark (rounded square with stylised activity glyph)
  const logoX = 14;
  const logoY = 7;
  const logoSize = 12;
  setFill(doc, BRAND.white);
  doc.roundedRect(logoX, logoY, logoSize, logoSize, 2.5, 2.5, "F");
  // Activity / pulse line
  setStroke(doc, BRAND.primary);
  doc.setLineWidth(0.9);
  const cx = logoX;
  const cy = logoY + logoSize / 2;
  doc.lines(
    [
      [1.6, 0],
      [1.2, -2.4],
      [1.6, 4.8],
      [1.6, -2.4],
      [1.6, 0],
      [2.4, 0],
    ],
    cx + 0.6,
    cy,
  );

  // Wordmark
  setText(doc, BRAND.white);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Coraçai", logoX + logoSize + 4, logoY + 5.4);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setText(doc, BRAND.white);
  doc.text("AI RADIOLOGY ASSIST", logoX + logoSize + 4, logoY + 10);

  // Right-side label
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("PATIENT REPORT", pageWidth - 14, logoY + 5.4, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text(
    new Date().toLocaleString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    }),
    pageWidth - 14,
    logoY + 10,
    { align: "right" },
  );

  setText(doc, BRAND.ink);
}

function drawFooter(doc: jsPDF, pageWidth: number, pageHeight: number, pageNum: number, total: number) {
  setStroke(doc, BRAND.border);
  doc.setLineWidth(0.2);
  doc.line(14, pageHeight - 16, pageWidth - 14, pageHeight - 16);

  setText(doc, BRAND.inkSoft);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text(
    "This report is generated by an AI-assisted tool and does not replace professional medical diagnosis.",
    14,
    pageHeight - 11,
  );
  doc.text(`Page ${pageNum} / ${total}`, pageWidth - 14, pageHeight - 11, { align: "right" });
  doc.text("coraçai • cardiomegaly screening", 14, pageHeight - 7);
}

function sectionTitle(doc: jsPDF, label: string, x: number, y: number) {
  setFill(doc, BRAND.primary);
  doc.rect(x, y - 3.2, 2.2, 4.2, "F");
  setText(doc, BRAND.ink);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(label.toUpperCase(), x + 4.5, y);
  doc.setFont("helvetica", "normal");
}

function infoCard(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  label: string,
  value: string,
) {
  setFill(doc, BRAND.surface);
  setStroke(doc, BRAND.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, h, 2, 2, "FD");

  setText(doc, BRAND.inkSoft);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text(label.toUpperCase(), x + 3.5, y + 5);

  setText(doc, BRAND.ink);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  const safeValue = value && value.length > 0 ? value : "—";
  const lines = doc.splitTextToSize(safeValue, w - 7);
  doc.text(lines.slice(0, 2), x + 3.5, y + 11);
  doc.setFont("helvetica", "normal");
}

function diagnosticBlock(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  scan: ReportScan,
) {
  const positive = scan.prediction === 1;
  const accent = positive ? BRAND.warning : BRAND.success;
  const probabilityPct = `${(scan.probability * 100).toFixed(1)}%`;

  setFill(doc, BRAND.surface);
  setStroke(doc, BRAND.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, 42, 2.5, 2.5, "FD");

  // Verdict badge
  setFill(doc, accent);
  doc.roundedRect(x + 5, y + 5, 38, 7, 1.5, 1.5, "F");
  setText(doc, BRAND.white);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(positive ? "DETECTED" : "NEGATIVE", x + 24, y + 9.8, { align: "center" });

  // Pathology label
  setText(doc, BRAND.ink);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(scan.pathology || "Cardiomegaly", x + 48, y + 11);

  // Verdict line
  setText(doc, BRAND.inkSoft);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const verdict = positive
    ? "Potential indication of cardiomegaly."
    : "No clear indication of cardiomegaly.";
  doc.text(verdict, x + 5, y + 19);

  // Confidence label
  setText(doc, BRAND.inkSoft);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("MODEL CONFIDENCE", x + 5, y + 26);

  setText(doc, BRAND.ink);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(probabilityPct, x + w - 5, y + 26, { align: "right" });

  // Bar
  const barX = x + 5;
  const barY = y + 29.5;
  const barW = w - 10;
  const barH = 3;
  setFill(doc, BRAND.border);
  doc.roundedRect(barX, barY, barW, barH, 1.2, 1.2, "F");
  setFill(doc, accent);
  const fillW = Math.max(2, Math.min(barW, barW * scan.probability));
  doc.roundedRect(barX, barY, fillW, barH, 1.2, 1.2, "F");

  // Caveat
  if (scan.probability < 0.9) {
    setText(doc, BRAND.warning);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(7.5);
    doc.text(
      "Confidence below 90%. Interpret with caution and specialist review.",
      x + 5,
      y + 38,
    );
  }
}

function stripMarkdown(input: string): string {
  return input
    .replace(/```[\s\S]*?```/g, (block) => block.replace(/```[a-z]*\n?|```/gi, ""))
    .replace(/`([^`]+)`/g, "$1")
    .replace(/!\[[^\]]*\]\([^)]+\)/g, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^\s{0,3}#{1,6}\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/_([^_]+)_/g, "$1")
    .replace(/^\s*>\s?/gm, "")
    .replace(/^\s*[-*+]\s+/gm, "•  ")
    .replace(/^\s*\d+\.\s+/gm, (m) => m.trim() + " ");
}

type Block = { kind: "heading" | "paragraph" | "bullet"; text: string };

function parseSummary(raw: string): Block[] {
  const cleaned = stripMarkdown(raw).replace(/\r\n/g, "\n");
  const lines = cleaned.split("\n");
  const blocks: Block[] = [];
  let buffer: string[] = [];

  const flushParagraph = () => {
    const text = buffer.join(" ").replace(/\s+/g, " ").trim();
    if (text.length > 0) blocks.push({ kind: "paragraph", text });
    buffer = [];
  };

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (line.length === 0) {
      flushParagraph();
      continue;
    }
    if (/^•\s+/.test(line)) {
      flushParagraph();
      blocks.push({ kind: "bullet", text: line.replace(/^•\s+/, "") });
      continue;
    }
    // Treat short ALL CAPS or trailing-colon lines as headings
    if (line.length <= 60 && /:$/.test(line) && /^[A-Z]/.test(line)) {
      flushParagraph();
      blocks.push({ kind: "heading", text: line.replace(/:$/, "") });
      continue;
    }
    buffer.push(line);
  }
  flushParagraph();
  return blocks;
}

export async function generateReport({ patient, scan, aiSummary }: ReportOptions): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  // -------- Page 1: Patient + diagnostic + image --------
  drawHeader(doc, pageWidth);
  let y = 38;

  // Title
  setText(doc, BRAND.ink);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Cardiomegaly Screening Report", margin, y);
  y += 6;
  setText(doc, BRAND.inkSoft);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    "AI-assisted classification of a chest radiograph for radiology review.",
    margin,
    y,
  );
  y += 9;

  // Patient + doctor info cards
  sectionTitle(doc, "Patient & clinician", margin, y);
  y += 5;
  const cardW = (pageWidth - margin * 2 - 6) / 3;
  infoCard(doc, margin, y, cardW, 16, "Patient name", patient.patientName);
  infoCard(doc, margin + cardW + 3, y, cardW, 16, "Patient ID", patient.patientId);
  infoCard(doc, margin + (cardW + 3) * 2, y, cardW, 16, "Reporting clinician", patient.doctorName || "—");
  y += 22;

  // Diagnostic
  sectionTitle(doc, "Diagnostic finding", margin, y);
  y += 5;
  diagnosticBlock(doc, margin, y, pageWidth - margin * 2, scan);
  y += 48;

  // Image
  sectionTitle(doc, "Radiograph", margin, y);
  y += 5;

  let imageData: { dataUrl: string; width: number; height: number } | null = null;
  try {
    imageData = await imageToDataUrl(scan.imageUrl);
  } catch {
    imageData = null;
  }

  const imgFrameX = margin;
  const imgFrameY = y;
  const imgFrameW = pageWidth - margin * 2;
  const remaining = pageHeight - y - 32;
  const imgFrameH = Math.min(110, remaining);

  setFill(doc, [10, 14, 24]);
  setStroke(doc, BRAND.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(imgFrameX, imgFrameY, imgFrameW, imgFrameH, 2.5, 2.5, "FD");

  if (imageData) {
    const ratio = imageData.width / imageData.height;
    const padding = 4;
    const availW = imgFrameW - padding * 2;
    const availH = imgFrameH - padding * 2;
    let drawW = availW;
    let drawH = drawW / ratio;
    if (drawH > availH) {
      drawH = availH;
      drawW = drawH * ratio;
    }
    const drawX = imgFrameX + (imgFrameW - drawW) / 2;
    const drawY = imgFrameY + (imgFrameH - drawH) / 2;
    doc.addImage(imageData.dataUrl, "JPEG", drawX, drawY, drawW, drawH, undefined, "FAST");
  } else {
    setText(doc, BRAND.white);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.text("Image preview unavailable.", imgFrameX + imgFrameW / 2, imgFrameY + imgFrameH / 2, {
      align: "center",
    });
  }

  setText(doc, BRAND.inkSoft);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(scan.imageName, margin, imgFrameY + imgFrameH + 4);

  // Notes (only if they fit on page 1)
  const notesY = imgFrameY + imgFrameH + 9;
  if (scan.notes && scan.notes.trim().length > 0 && notesY < pageHeight - 30) {
    sectionTitle(doc, "Clinical notes", margin, notesY);
    setText(doc, BRAND.ink);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    const wrapped = doc.splitTextToSize(scan.notes.trim(), pageWidth - margin * 2);
    const maxLines = Math.max(0, Math.floor((pageHeight - notesY - 22) / 4.5));
    doc.text(wrapped.slice(0, maxLines), margin, notesY + 6);
  }

  // -------- Page 2: AI Summary --------
  if (aiSummary && aiSummary.trim().length > 0) {
    doc.addPage();
    drawHeader(doc, pageWidth);

    let py = 38;
    setText(doc, BRAND.ink);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("AI Clinical Summary", margin, py);
    py += 6;

    setText(doc, BRAND.inkSoft);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(
      "Generative summary of the case for clinician triage. Not a substitute for expert review.",
      margin,
      py,
    );
    py += 8;

    // Subtle context strip
    setFill(doc, BRAND.surface);
    setStroke(doc, BRAND.border);
    doc.setLineWidth(0.3);
    doc.roundedRect(margin, py, pageWidth - margin * 2, 14, 2, 2, "FD");
    setText(doc, BRAND.inkSoft);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(
      `Patient: ${patient.patientName || "—"}   ·   ID: ${patient.patientId || "—"}   ·   Pathology: ${scan.pathology || "Cardiomegaly"}`,
      margin + 4,
      py + 5.5,
    );
    doc.text(
      `Confidence: ${(scan.probability * 100).toFixed(1)}%   ·   Verdict: ${scan.prediction === 1 ? "Detected" : "Negative"}`,
      margin + 4,
      py + 10,
    );
    py += 20;

    // Render parsed summary
    const blocks = parseSummary(aiSummary);
    const contentX = margin;
    const contentW = pageWidth - margin * 2;
    const lineH = 4.6;

    for (const block of blocks) {
      if (py > pageHeight - 25) {
        doc.addPage();
        drawHeader(doc, pageWidth);
        py = 38;
      }

      if (block.kind === "heading") {
        py += 2;
        setText(doc, BRAND.primary);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.text(block.text, contentX, py);
        py += 5.5;
        setStroke(doc, BRAND.border);
        doc.setLineWidth(0.2);
        doc.line(contentX, py - 1.5, contentX + 28, py - 1.5);
        py += 1;
        continue;
      }

      if (block.kind === "bullet") {
        setFill(doc, BRAND.primary);
        doc.circle(contentX + 1.4, py - 1.2, 0.9, "F");
        setText(doc, BRAND.ink);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        const wrapped = doc.splitTextToSize(block.text, contentW - 6);
        doc.text(wrapped, contentX + 4.5, py);
        py += wrapped.length * lineH + 1.2;
        continue;
      }

      // paragraph
      setText(doc, BRAND.ink);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      const wrapped = doc.splitTextToSize(block.text, contentW);
      // Page-break aware paragraph rendering
      let i = 0;
      while (i < wrapped.length) {
        if (py > pageHeight - 22) {
          doc.addPage();
          drawHeader(doc, pageWidth);
          py = 38;
        }
        const linesPerPage = Math.max(1, Math.floor((pageHeight - 22 - py) / lineH));
        const slice = wrapped.slice(i, i + linesPerPage);
        doc.text(slice, contentX, py);
        py += slice.length * lineH;
        i += slice.length;
      }
      py += 2.5;
    }
  }

  // Footers on every page
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    drawFooter(doc, pageWidth, pageHeight, p, total);
  }

  return doc;
}

export function safeFilenameFragment(input: string, fallback: string): string {
  const cleaned = input
    .trim()
    .replace(/[^\p{L}\p{N}_-]+/gu, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
  return cleaned.length > 0 ? cleaned : fallback;
}
